services:
  server:
    build: ./server

    ports:
      - "1571:1571"

    env_file:
      - ./server/.env

    volumes:
      - ./server:/app
      - /app/node_modules

    command: npm run dev

    restart: unless-stopped