services:
  server:
    build: ./server

    ports:
      - "1571:1571"

    env_file:
      - ./server/.env.production

    environment:
      NODE_ENV: production

    command: npm start

    restart: unless-stopped

    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped