name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  server-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    env:
      NODE_ENV: test
      DISABLE_EMAIL: "true"
      MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm test

  deploy:
    needs: server-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}