name: Run Tests

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  server-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    env:
      MONGO_URI_TEST: mongodb+srv://PatelJay345:Jayamar1976@cluster0.jdzy3tv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 #  ADD THIS

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm test
